### ISSUE TITLE
Each time you open a picker, the time will change (timezone + custom format)

### ISSUE THREAD

**Issue by tmotyl** [Eonasdan/bootstrap-datetimepicker#1356]
In current timezone implemnetation in the method getMoment
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L157

there is a code to compare configured timezone with browser timezone.
This is plainly wrong. if timezone is set on datepicker we should not consider browser timezone at all, and assume that provided date string is already in the configured timezone.

The current implementation leads to issues, when you have different timezone configured in the picker and in the browser. Each time you open a datepicker your time will change.

I fixed it by changing

```
if (tzEnabled) {
  currentZoneOffset = moment().tz(options.timeZone).utcOffset();
  incomingZoneOffset = moment(d, parseFormats, options.useStrict).utcOffset();
  if (incomingZoneOffset !== currentZoneOffset) {
    timeZoneIndicator = moment().tz(options.timeZone).format('Z');
    dateWithTimeZoneInfo = moment(d, parseFormats, options.useStrict).format('YYYY-MM-DD[T]HH:mm:ss') + timeZoneIndicator;
    returnMoment = moment(dateWithTimeZoneInfo, parseFormats, options.useStrict).tz(options.timeZone);
  } else {
     returnMoment = moment(d, parseFormats, options.useStrict).tz(options.timeZone);
   }
} else {
```

to

```
if (tzEnabled) {
 returnMoment = moment.tz(d, parseFormats, options.timeZone);
  } else {
```

this will also resolve issue: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1355

**Comment by tmotyl** [comment]
just found out that the same solution is used in pull request for issue https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1326

https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1329

**Comment by thibaultlavoisey** [comment]
@tmotyl You saved my day, thank's!

**Comment by smisch** [comment]
+1 to fix this. 

took me hours to find out what the problem was. who would have guessed that the timezones plugin was the cause.

**Comment by tmotyl** [comment]
looks like the fix was merged to development branch already https://github.com/Eonasdan/bootstrap-datetimepicker/commit/ac17a1c7e3bc291448cce4cafa454e98140c8da6

**Comment by adamgins** [comment]
Hi folks, great plugin but was running into similar timezone issues. Is this released yet? Also any example on how we're meant to be using timezones, pls? When I get a `dp.onchange` that date has a timezone of `+00:00` event though I am in timezone `+11:001`

**Comment by Condor2708** [comment]
+1 timezone examples required

**Comment by ehannes** [comment]
This update is still missing on the master branch, right? When will it be included?

**Comment by guy-roberts** [comment]
I am glad to find this,  it was driving me nuts. Thanks.

**Comment by cerdiogenes** [comment]
+1 for a release with this fix!

**Comment by kyranb** [comment]
Any update on this?

**Comment by guy-roberts** [comment]
It would be good to see this in the master branch

**Comment by rchanou** [comment]
This appears to be working as of the latest release version, it's just not documented! Pass in `timeZone` (capital "Z") into the init options.

**Comment by William-H-M** [comment]
AS @rchanou said this has been solved here a [Fiddle](http://jsfiddle.net/tyw9dnhb)
